x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_COOKIE_SECRET: "xxxxxx" # 任意の文字列を設定してください

services:

  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      <<: *redash-environment
    depends_on:
      - postgres
      - redis
    restart: always

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      <<: *redash-environment
    depends_on:
      - postgres
      - redis
    restart: always

  worker:
    <<: *redash-service
    command: worker
    environment:
      <<: *redash-environment
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    image: redis:7.2.4
    restart: always

  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    restart: always

  create_db:
    <<: *redash-service
    command: create_db
    environment:
      <<: *redash-environment
    depends_on:
      - postgres
      - redis
    profiles:
      - create_db
